name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Install deps
      run: npm install
    
    - name: Build React App
      run: npm run build
        
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to Surge
      run: surge ./ wasteful-paint.surge.sh --token ${{ secrets.SURGE_TOKEN}}
#      
